import type { ReactNode } from "react";

export type BadgeTone = "neutral" | "pass" | "warn" | "fail" | "info" | "demo";

const GLYPHS: Record<BadgeTone, string> = {
  neutral: "○",
  pass: "✓",
  warn: "▲",
  fail: "✕",
  info: "●",
  demo: "◆",
};

export interface BadgeProps {
  tone?: BadgeTone;
  children: ReactNode;
  title?: string;
}

/** Status chip. Always renders a glyph and text so meaning never depends on colour alone. */
export function Badge({ tone = "neutral", children, title }: BadgeProps) {
  return (
    <span className={`mdx-badge mdx-badge--${tone}`} title={title}>
      <span className="mdx-badge__glyph" aria-hidden="true">
        {GLYPHS[tone]}
      </span>
      {children}
    </span>
  );
}

export type CheckStatusValue = "PASS" | "WARN" | "FAIL" | "SKIPPED";

const STATUS_TONE: Record<CheckStatusValue, BadgeTone> = {
  PASS: "pass",
  WARN: "warn",
  FAIL: "fail",
  SKIPPED: "neutral",
};

export function StatusPill({ status }: { status: CheckStatusValue }) {
  return <Badge tone={STATUS_TONE[status]}>{status}</Badge>;
}

export type OriginValue = "simulated" | "measured";

/**
 * Marks data provenance. `simulated` data must always carry this badge; the desktop never
 * presents mock values as measurements.
 */
export function OriginBadge({ origin }: { origin: OriginValue }) {
  return origin === "simulated" ? (
    <Badge tone="demo" title="Generated by a mock provider. Not measured from real hardware.">
      Simulated
    </Badge>
  ) : (
    <Badge tone="info">Measured</Badge>
  );
}
