import { z } from "zod";

/** Version of the structured runtime protocol. Bump on any breaking contract change. */
export const PROTOCOL_VERSION = "0.1.0";

/**
 * Who produced a value.
 *
 * - `simulated`: generated by a mock/demo/synthetic provider. The UI must label it as such.
 * - `measured`: obtained from an actual runtime, software tool, operating system or
 *   physical device observation. This does not imply physical MDX hardware exists.
 * Nested records retain their own provenance; MDX mock data remains simulated.
 */
export const OriginSchema = z.enum(["simulated", "measured"]);
export type Origin = z.infer<typeof OriginSchema>;

/** Stable identifier used for projects, jobs and runs. */
export const IdSchema = z
  .string()
  .regex(/^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/, "must be 1-64 chars of [A-Za-z0-9_-]");

export const IsoTimestampSchema = z.iso.datetime({ offset: true });

/**
 * A path relative to the project root, always POSIX-separated.
 *
 * The runtime owns the Windows <-> WSL path mapping; the desktop never sends absolute paths,
 * drive letters, parent-directory segments or shell metacharacters. The pattern is
 * intentionally strict and may be relaxed by the runtime in a later protocol version.
 */
export const PROJECT_PATH_PATTERN =
  /^(?!\.{1,2}(?:\/|$))(?:[A-Za-z0-9._+@=-]+)(?:\/(?!\.{1,2}(?:\/|$))[A-Za-z0-9._+@=-]+)*$/;

export const ProjectPathSchema = z
  .string()
  .max(255)
  .regex(PROJECT_PATH_PATTERN, "must be a relative POSIX path without '..' or special characters");
export type ProjectPath = z.infer<typeof ProjectPathSchema>;

/** A directory inside the project: the project root (`.`) or a relative path. */
export const ProjectDirectorySchema = z.union([z.literal("."), ProjectPathSchema]);

/** Returns a path schema that also requires one of the given (lower-case) extensions. */
export function projectPathWithExtension(extensions: readonly string[]) {
  const alternatives = extensions.map((ext) => ext.replace(/[^A-Za-z0-9]/g, "")).join("|");
  return ProjectPathSchema.regex(
    new RegExp(`\\.(?:${alternatives})$`),
    `must end with one of: ${extensions.map((e) => `.${e}`).join(", ")}`,
  );
}

/** Simple identifier-like name, e.g. an output basename. */
export const SafeNameSchema = z
  .string()
  .regex(/^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/, "must be 1-64 chars of [A-Za-z0-9_-]");

export const Sha256DigestSchema = z.string().regex(/^[a-f0-9]{64}$/, "must be a lowercase sha256");
